openapi: 3.0.1
info:
  title: Posts API
  description: API for creating, retrieving, updating, and deleting posts
  version: 1.0.0
servers:
  - url: https://api.example.com/posts
paths:
  /:
    post:
      summary: Create a new post
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "201":
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
  /{post_id}:
    get:
      summary: Get a post by ID
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retrieved post successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
    put:
      summary: Update a post
      security:
        - BearerAuth: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "200":
          description: Post updated successfully
    delete:
      summary: Delete a post
      security:
        - BearerAuth: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Post deleted successfully
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        username:
          type: string
        avatar_url:
          type: string
        timestamp:
          type: string
          format: date-time
        content:
          type: string
        media_items:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              type:
                type: string
              alt_text:
                type: string
        interaction_settings:
          type: array
          items:
            type: object
            properties:
              action:
                type: string
              effect:
                type: string
              value:
                type: string
        is_edited:
          type: boolean
        edited_timestamp:
          type: string
          format: date-time
        is_deleted:
          type: boolean
