# Use the official Python slim image
FROM python:3.12-slim

# Install system dependencies (for geospatial libraries)
RUN apt-get update && apt-get install -y \
    libspatialindex-dev \
    && apt-get clean

# Install required Python packages
RUN pip install --no-cache-dir \
    boto3 \
    pandas \
    pyarrow \
    geopandas \
    shapely \
    rtree \
    flask

# Copy application code
COPY app.py /app.py

# Expose the port Flask will run on
EXPOSE 8080

# Specify the entry point for running the Flask application
ENTRYPOINT ["python", "/app.py"]
